In [1]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [12]:
N=5
x = np.arange(N, 0, -1) - 1
print(x)
type(x)

[4 3 2 1 0]


numpy.ndarray

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [22]:
N=5
m = np.diag(np.arange(N,0,-1) -1)
print(m)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [23]:
np.sum(m)

10

Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [36]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
v = linalg.solve(a, b)
v

array([ 0.46666667,  3.84444444, -5.55555556])

In [37]:
np.allclose( np.dot(a, v), b )

True

In [38]:
np.dot(a, v)

array([ 4., 12., -3.])

In [40]:
v*9

array([  4.2,  34.6, -50. ])

Задание 4

In [41]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [42]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [43]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [44]:
users_stats[2]

array([2, 0, 1, 0, 0, 0], dtype=int32)

In [56]:
user_id=1
maxVal = 0
maxUser = 0
print("id cos stats")
for row in users_stats:
    c = cosine(row, next_user_stats)
    print(user_id, c, row)
    if c > maxVal:
        maxVal = c
        maxUser = user_id
    user_id+=1
print()
print("Самый похожий пользователь id =", maxUser, " stats =", users_stats[maxUser-1])

id cos stats
1 0.19999999999999996 [2 1 0 0 0 0]
2 0.8451542547285165 [1 1 2 1 0 0]
3 0.3999999999999999 [2 0 1 0 0 0]
4 0.7905694150420948 [1 1 2 1 0 1]
5 0.3999999999999999 [0 0 1 2 0 0]
6 0.0 [0 0 0 0 0 5]
7 0.0 [1 0 0 0 0 0]
8 0.9486832980505138 [0 1 1 0 0 0]
9 0.0 [0 0 0 1 1 3]
10 0.0 [1 0 0 2 1 4]

Самый похожий пользователь id = 8  stats = [0 1 1 0 0 0]
